### ISSUE TITLE
Provide pre-trained models

### ISSUE THREAD

**Issue by Daanielvb** [arop/ner-re-pt#1]
Is there any way you could provide here or on a file storage service one of your pre-trained NER models? I'm struggling to create a custom Portuguese Chunker and NER tagger following your methodology. So it would be a great contribution to have a least one of the NLTK models

**Comment by arop** [comment]
I already did. Go to the wiki of this project, to the page "Resources". You'll find there links to my trained models.

**Comment by Daanielvb** [comment]
Thanks for pointing the resources. I have managed to download it. 

I observe that there are some pre-trained pickle models using different approaches (naive bayes, max-entropy). However, one thing that I did not understand was the difference between subtypes-min, types-min and cat-min . Are all these NER taggers trained exclusively to identify just these 3 categories?

**update:**
While using your tag on my dataset, I have observed some named entities that were not so obvious to me, like "OBRA". Do you have any list of the entities and their meaning?

**Comment by arop** [comment]
The HAREM dataset includes "nested" categories. 
I provided a list on this wiki, check the HAREM page. I don't own the dataset.
You have to read more on that ([link](https://github.com/arop/ner-re-pt/wiki/HAREM-collection)).
